name: Install NGINX
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure the SSH Private Key Secret
        run: |
           mkdir -p ~/.ssh/
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           eval "$(ssh-agent -s)"
           ssh-add ~/.ssh/id_rsa
      - name: Set Strict Host Key Checking
          run: |
            echo "Host *" > ~/.ssh/config
            echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            chmod 600 ~/.ssh/config
      - name: Install NGINX
        run: |
          export MY_HOST="${{ secrets.AKAMAI_INSTANCE_IP_ADDRESS }}"
          ssh -F ~/.ssh/config root@${MY_HOST} sudo apt update
          ssh -F ~/.ssh/config root@${MY_HOST} sudo apt install nginx -y
